version: "3.9"

services:
  web:
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_web.entrypoints=http
    build:
      x-bake:
        tags: ${COMPOSE_PROJECT_NAME}_web:latest
        cache-from: type=local,src=/tmp/cache/${COMPOSE_PROJECT_NAME}_web
        cache-to: type=local,mode=max,dest=/tmp/cache/${COMPOSE_PROJECT_NAME}_web
        output: type=docker,dest=${COMPOSE_PROJECT_NAME}_web.tar
    image: ${COMPOSE_PROJECT_NAME}_web:latest
    volumes:
      - ./public:/app/public
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    name: traefik
