version: "3.9"

networks:
  traefik:
    name: traefik

services:
  app:
    build:
      x-bake:
        output: type=docker,dest=./${COMPOSE_PROJECT_NAME}-app.tar.gz
    image: ${COMPOSE_PROJECT_NAME}-app:latest
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.rule=Host(`${DOMAIN:-${COMPOSE_PROJECT_NAME}.localhost}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-app.entrypoints=web
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-app.loadbalancer.server.port=5173
