version: "3.9"

name: nest-apollo

services:
  postgres:
    env_file: .env
    image: postgres:13.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - database
    healthcheck:
      test: pg_isready -q
      start_period: 5s
      interval: 5s
    restart: unless-stopped

  api:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.nest-apollo_api--strip-api.stripprefix.prefixes=/api
      - traefik.http.middlewares.nest-apollo_api--strip-api.stripprefix.forceSlash=false
      - traefik.http.routers.nest-apollo_api.rule=Host(`nest-apollo.example.com`) && PathPrefix(`/api`)
      - traefik.http.routers.nest-apollo_api.middlewares=nest-apollo_api--strip-api
      - traefik.http.routers.nest-apollo_api.entrypoints=http
    depends_on:
      - postgres
    env_file: .env
    build:
      x-bake:
        tags: nest-apollo_api:latest
        cache-from: type=local,src=/tmp/cache/nest-apollo_api
        cache-to: type=local,mode=max,dest=/tmp/cache/nest-apollo_api
        output: type=docker,dest=nest-apollo_api.tar
    image: nest-apollo_api:latest
    volumes:
      - ./public:/app/public
    networks:
      - database
      - traefik
    restart: unless-stopped

volumes:
  postgres:

networks:
  database:
  traefik:
    name: traefik
