version: '3.8'

services:
  postgres:
    env_file:
      - .env.local
    image: postgres:13.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    restart: unless-stopped

  app:
    depends_on:
      - postgres
    env_file:
      - .env.local
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.${NAME}.rule=Host(`${DOMAIN}`)
#      - traefik.http.routers.${NAME}.entrypoints=web
#      - traefik.http.services.${NAME}.loadbalancer.server.port=${PORT}
    build: .
    volumes:
      - $PWD/public:/app/public
    networks:
#      - traefik
      - backend
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    restart: unless-stopped

volumes:
  postgres:

networks:
#  traefik:
#    external:
#      name: "traefik"
  backend:
